name: generate-html
on:
  push:
    paths:
      - "index.md"
    branches:
      - master
jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: "pandoc --standalone --metadata pagetitle=\"yohello\" --css \"assets/css/pandoc.css\" --output=index.html index.md"
      - name: Commit
        run: |
          git config --global user.name "ktvng"
          git config --global user.email "35818433+ktvng@users.noreply.github.com"
          git add index.html
          git commit -m "[BOT] Generate HTML from Markdown"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
